### ISSUE TITLE
devlist with multiple devices only loads a single device.

### ISSUE THREAD

**Issue by lcruy** [ferflechas/udi-tuya-poly_v2#1]
First thanks for the nodeserver.

I have a devlist yaml with 2 devices but only the first device is shown and controllable.

Here are samples of what I have tried:

File 1
devices:
- name: novostella1
  ip: 10.100.100.133
  ver: 3.3
  id: 5623xxxxxxxxxxxxx1bc
  key: f59d0xxxxxxxxa55
  type: bulb
- name: novostella2
  ip: 10.100.100.146
  ver: 3.3
  id: 5623xxxxxxxxxxxxxccc
  key: 7faexxxxxxxxa14
  type: bulb

File 2:
devices:
- name: novostella1
  ip: 10.100.100.133
  ver: 3.3
  id: 5623xxxxxxxxxxxxx1bc
  key: f59d0xxxxxxxxa55
  type: bulb

- name: novostella2
  ip: 10.100.100.146
  ver: 3.3
  id: 5623xxxxxxxxxxxxxccc
  key: 7faexxxxxxxxa14
  type: bulb

**Comment by ferflechas** [comment]
@lcruy please try without linespaces and with correct indents, also check your device IP/ID/Key (_i have around 10 bulbs/outlets running without issues_)
---------------------------------------------
```
devices:
- name: novostella1
  ip: 10.100.100.133
  ver: 3.3
  id: 5623xxxxxxxxxxxxx1bc
  key: f59d0xxxxxxxxa55
  type: bulb
- name: novostella2
  ip: 10.100.100.146
  ver: 3.3
  id: 5623xxxxxxxxxxxxxccc
  key: 7faexxxxxxxxa14
  type: bulb
```
---------------------------------------------
